%% ======================================================================
% SYN_ML_SVR_SOH_LoadCV_Bayes.m
% ----------------------------------------------------------------------
% Synthetic DRT-SOH dataset -> SVR with load-level CV and Bayesian tuning
%
% [DATA]
%   Input MAT/CSV is generated by Synthesis_DRT_SOH.m
%   Required table columns:
%     Feature: R0_hat, R1_hat, R2_hat, tau1_hat, tau2_hat
%     Label  : SOH_DRT
%     Group  : load_name
%
% [SPLIT]
%   Load-level split.
%   If total loads = 20:
%     fixed test loads = 4
%     remaining train/val loads = 16
%     K-fold CV with K=4 -> each fold train:val:test = 12:4:4 loads
%
% [MODEL]
%   Support Vector Regression using fitrsvm.
%
% [TUNING]
%   TUNE_MODE = "bayes" uses bayesopt with a custom objective function.
%   The objective is the pooled load-CV RMSE/MAE on development loads.
% ======================================================================
clear; clc; close all;

set(groot,'defaultTextInterpreter','none');
set(groot,'defaultAxesTickLabelInterpreter','none');
set(groot,'defaultLegendInterpreter','none');

%% ----------------------------- CONFIG --------------------------------
DATA_PATH = "G:\공유 드라이브\Battery Software Group (2025)\Members\김주은\PINN\합성데이터\Synthetic_DRT_SOH_Dataset_DRTLabel_CellRef.mat";
SAVE_DIR  = "G:\공유 드라이브\Battery Software Group (2025)\Members\김주은\PINN\합성데이터\ML_SVR";
if ~exist(SAVE_DIR, 'dir'), mkdir(SAVE_DIR); end

FEATURE_NAMES = {'R0_hat','R1_hat','R2_hat','tau1_hat','tau2_hat'};
LABEL_NAME    = 'SOH_DRT';
LOAD_COL      = 'load_name';

% PSD feature setting.
USE_PSD_FEATURE = true;
PSD_MAT_PATH = "G:\공유 드라이브\Battery Software Lab\Protocols\2025 현대 NE 고품셀 평가 실험\주행부하_scaledown\PSD\psd_stat_tbl.mat";

% PSD_feature.m output column names to append.
% Recommended set used in the driving-load selection workflow:
%   log transform for energy/frequency features, no log for f_geo_std_dec.
PSD_FEAT_USE = [ ...
    "E_slow_fast_ratio", ...
    "f_geo_mean_Hz", ...
    "f_geo_std_dec", ...
    "f_fast_geo_mean_Hz", ...
    "f_slow_geo_mean_Hz" ...
    ];
PSD_FEAT_TRANSFORM = [ ...
    "log10", ...
    "log10", ...
    "none", ...
    "log10", ...
    "log10" ...
    ];

if numel(PSD_FEAT_USE) ~= numel(PSD_FEAT_TRANSFORM)
    error('PSD_FEAT_USE and PSD_FEAT_TRANSFORM must have the same length.');
end


USE_ONLY_CONVERGED_FIT = true;
USE_LOG_FEATURES = true;
STANDARDIZE_X = true;           % fitrsvm built-in standardization

RNG_SEED = 1;
N_TEST_LOAD = 4;
N_VAL_LOAD_PER_FOLD = 4;
TEST_LOAD_STR = "";             % e.g. "US06 UDDS HWFET WLTP". Empty -> random 4 loads

% Hyperparameter tuning.
%   "fixed"  : use FIXED_* settings
%   "random" : random search over candidates
%   "bayes"  : Bayesian optimization using load-level CV objective
TUNE_MODE = "bayes";            % "fixed" | "random" | "bayes"
TUNE_METRIC = "RMSE";           % "RMSE" | "MAE"

% Fixed setting.
FIXED_KERNEL = 'linear';         % 'linear' | 'gaussian'
FIXED_C = 10;
FIXED_EPSILON = 0.05;
FIXED_KERNELSCALE = 'auto';

% Random(+Bayesian) search setting.
RAND_N_TRIALS = 200;
RAND_KERNEL_SET = {'linear','gaussian'};
RAND_C_RANGE_LOG10   = [-3, 3];  % 1e-3 ~ 1e3
RAND_EPS_RANGE_LOG10 = [-4, 0];  % 1e-4 ~ 1
RAND_KS_RANGE_LOG10  = [-3, 3];  % gaussian only
RAND_USE_AUTO_KERNELSCALE = true;

% Bayesian optimization setting.
BAYES_MAX_EVALS = 80;            % each evaluation runs K load-CV fits
BAYES_NUM_SEED_POINTS = 20;
BAYES_ACQ = 'expected-improvement-plus';
BAYES_VERBOSE = 1;
BAYES_SHOW_PLOTS = false;

EARLYSTOP_ENABLE = false;        % used only for random search
EARLYSTOP_PATIENCE = 30;
EARLYSTOP_MIN_IMPROVE = 1e-5;

MAKE_PLOTS = true;

%% ----------------------------- LOAD DATA -----------------------------
Dataset = localLoadSyntheticDataset(DATA_PATH);

needCols = [FEATURE_NAMES, {LABEL_NAME, LOAD_COL}];
for i = 1:numel(needCols)
    if ~ismember(needCols{i}, Dataset.Properties.VariableNames)
        error('Dataset does not contain required column: %s', needCols{i});
    end
end

X = Dataset{:, FEATURE_NAMES};
y = Dataset{:, LABEL_NAME};
load_id = string(Dataset{:, LOAD_COL});

valid = all(isfinite(X),2) & isfinite(y) & strlength(load_id)>0;
if USE_ONLY_CONVERGED_FIT && ismember('exitflag', Dataset.Properties.VariableNames)
    valid = valid & Dataset.exitflag > 0;
end

X = X(valid,:);
y = y(valid,:);
load_id = load_id(valid,:);

if USE_LOG_FEATURES
    if any(X(:) <= 0)
        error('USE_LOG_FEATURES=true but some ECM features are <= 0. Check fitted parameters.');
    end
    X = log10(X);
    feat_names_used = strcat('log10_', FEATURE_NAMES);
else
    feat_names_used = FEATURE_NAMES;
end

% Append load-level PSD features.
% PSD features are load-specific, so the same PSD vector is broadcast to all
% synthetic samples with the same load_name.
if USE_PSD_FEATURE
    [X_psd, psd_feat_names, psd_info] = localBuildPSDFeatureMatrix( ...
        PSD_MAT_PATH, load_id, PSD_FEAT_USE, PSD_FEAT_TRANSFORM);
    X = [X, X_psd];
    feat_names_used = [feat_names_used, psd_feat_names];
else
    psd_info = struct();
end

valid2 = all(isfinite(X),2) & isfinite(y) & strlength(load_id)>0;
if nnz(valid2) < numel(valid2)
    fprintf('[PSD] Removed %d samples with non-finite ECM/PSD features after PSD merge.\n', nnz(~valid2));
    X = X(valid2,:);
    y = y(valid2,:);
    load_id = load_id(valid2,:);
end

all_loads = unique(load_id, 'stable');
nLoads = numel(all_loads);
fprintf('[DATA] valid samples = %d | loads = %d | features = %d\n', size(X,1), nLoads, size(X,2));
fprintf('[FEATURES] %s\n', strjoin(string(feat_names_used), ', '));
fprintf('[LOADS] %s\n', strjoin(cellstr(all_loads), ', '));

%% ----------------------------- LOAD SPLIT ----------------------------
rng(RNG_SEED, 'twister');

if strlength(strtrim(TEST_LOAD_STR)) > 0
    test_loads = parseLoadList(TEST_LOAD_STR);
    test_loads = intersect(test_loads, all_loads, 'stable');
else
    if nLoads < N_TEST_LOAD + N_VAL_LOAD_PER_FOLD
        error('Not enough loads for requested split. nLoads=%d', nLoads);
    end
    p = randperm(nLoads);
    test_loads = all_loads(sort(p(1:N_TEST_LOAD)));
end

trainval_loads = setdiff(all_loads, test_loads, 'stable');
if mod(numel(trainval_loads), N_VAL_LOAD_PER_FOLD) ~= 0
    warning('numel(trainval_loads)=%d is not divisible by N_VAL_LOAD_PER_FOLD=%d. Last fold size may differ.', ...
        numel(trainval_loads), N_VAL_LOAD_PER_FOLD);
end
K = ceil(numel(trainval_loads) / N_VAL_LOAD_PER_FOLD);

p = randperm(numel(trainval_loads));
cv_loads_shuffled = trainval_loads(p);
fold_val_loads = cell(K,1);
for k = 1:K
    idx1 = (k-1)*N_VAL_LOAD_PER_FOLD + 1;
    idx2 = min(k*N_VAL_LOAD_PER_FOLD, numel(cv_loads_shuffled));
    fold_val_loads{k} = cv_loads_shuffled(idx1:idx2);
end

fprintf('\n[SPLIT]\n');
fprintf('  Test loads (%d): %s\n', numel(test_loads), strjoin(cellstr(test_loads), ', '));
fprintf('  Train/Val loads (%d): %s\n', numel(trainval_loads), strjoin(cellstr(trainval_loads), ', '));
fprintf('  CV folds = %d | val loads per fold = %d\n', K, N_VAL_LOAD_PER_FOLD);

%% ----------------------------- TUNE BY LOAD-CV -----------------------
fprintf('\n[TUNING] mode=%s | metric=%s\n', TUNE_MODE, TUNE_METRIC);
results_bayes = [];

if TUNE_MODE == "fixed"

    bestCand = struct( ...
        'KernelFunction', FIXED_KERNEL, ...
        'BoxConstraint', FIXED_C, ...
        'Epsilon', FIXED_EPSILON, ...
        'KernelScale', FIXED_KERNELSCALE);

    [bestScore, bestDetail] = evalLoadCV_SVR(X, y, load_id, trainval_loads, fold_val_loads, ...
        bestCand.KernelFunction, bestCand.BoxConstraint, bestCand.Epsilon, ...
        bestCand.KernelScale, STANDARDIZE_X, TUNE_METRIC);

elseif TUNE_MODE == "random"

    candidates = makeRandomCandidates(RAND_N_TRIALS, RAND_KERNEL_SET, ...
        RAND_C_RANGE_LOG10, RAND_EPS_RANGE_LOG10, RAND_KS_RANGE_LOG10, RAND_USE_AUTO_KERNELSCALE);

    bestScore = inf;
    bestIdx = NaN;
    bestDetail = struct();
    noImprove = 0;

    fprintf('  candidates=%d\n', numel(candidates));

    for ci = 1:numel(candidates)
        c = candidates(ci);

        [score, detail] = evalLoadCV_SVR(X, y, load_id, trainval_loads, fold_val_loads, ...
            c.KernelFunction, c.BoxConstraint, c.Epsilon, c.KernelScale, ...
            STANDARDIZE_X, TUNE_METRIC);

        if score < bestScore - EARLYSTOP_MIN_IMPROVE
            bestScore = score;
            bestIdx = ci;
            bestDetail = detail;
            noImprove = 0;
            fprintf('  Trial %03d/%03d | BEST %s=%.5f | kernel=%s C=%.4g eps=%.4g ks=%s\n', ...
                ci, numel(candidates), TUNE_METRIC, bestScore, ...
                c.KernelFunction, c.BoxConstraint, c.Epsilon, ks2str(c.KernelScale));
        else
            noImprove = noImprove + 1;
        end

        if mod(ci,25)==0
            fprintf('  Trial %03d/%03d | current best %s=%.5f\n', ...
                ci, numel(candidates), TUNE_METRIC, bestScore);
        end

        if EARLYSTOP_ENABLE && noImprove >= EARLYSTOP_PATIENCE
            fprintf('  Early stopped at trial %d.\n', ci);
            break;
        end
    end

    bestCand = candidates(bestIdx);

elseif TUNE_MODE == "bayes"

    vars = [
        optimizableVariable('kernelType', [1 2], 'Type', 'integer')
        optimizableVariable('log10C', RAND_C_RANGE_LOG10)
        optimizableVariable('log10Epsilon', RAND_EPS_RANGE_LOG10)
        optimizableVariable('log10KernelScale', RAND_KS_RANGE_LOG10)
    ];

    objFcn = @(T) bayesObjectiveLoadCV_SVR(T, X, y, load_id, ...
        trainval_loads, fold_val_loads, STANDARDIZE_X, TUNE_METRIC);

    if BAYES_SHOW_PLOTS
        plotFcnUse = {@plotMinObjective, @plotObjectiveModel};
    else
        plotFcnUse = [];
    end

    results_bayes = bayesopt(objFcn, vars, ...
        'MaxObjectiveEvaluations', BAYES_MAX_EVALS, ...
        'NumSeedPoints', BAYES_NUM_SEED_POINTS, ...
        'AcquisitionFunctionName', BAYES_ACQ, ...
        'IsObjectiveDeterministic', true, ...
        'Verbose', BAYES_VERBOSE, ...
        'PlotFcn', plotFcnUse);

    bestT = bestPoint(results_bayes);
    bestCand = bayesTableToCandidate(bestT);

    [bestScore, bestDetail] = evalLoadCV_SVR(X, y, load_id, trainval_loads, fold_val_loads, ...
        bestCand.KernelFunction, bestCand.BoxConstraint, bestCand.Epsilon, ...
        bestCand.KernelScale, STANDARDIZE_X, TUNE_METRIC);

else
    error('Unknown TUNE_MODE: %s', TUNE_MODE);
end

fprintf('\n[BEST SVR]\n');
fprintf('  kernel=%s | C=%.6g | epsilon=%.6g | KernelScale=%s\n', ...
    bestCand.KernelFunction, bestCand.BoxConstraint, bestCand.Epsilon, ks2str(bestCand.KernelScale));
fprintf('  Best objective %s=%.6f\n', TUNE_METRIC, bestScore);
fprintf('  CV: R2=%.4f | RMSE=%.4f | MAE=%.4f\n', ...
    bestDetail.metrics_pooled.R2, bestDetail.metrics_pooled.RMSE, bestDetail.metrics_pooled.MAE);

%% ----------------------------- FINAL TEST ----------------------------
is_tv = ismember(load_id, trainval_loads);
is_test = ismember(load_id, test_loads);

final_model = fitrsvm(X(is_tv,:), y(is_tv), ...
    'KernelFunction', bestCand.KernelFunction, ...
    'BoxConstraint', bestCand.BoxConstraint, ...
    'Epsilon', bestCand.Epsilon, ...
    'KernelScale', bestCand.KernelScale, ...
    'Standardize', STANDARDIZE_X);

yhat_test = predict(final_model, X(is_test,:));
test_metrics = calcMetrics(y(is_test), yhat_test);

fprintf('\n[FINAL TEST]\n');
fprintf('  Train loads = %d | Test loads = %d\n', numel(trainval_loads), numel(test_loads));
fprintf('  Test: R2=%.4f | RMSE=%.4f | MAE=%.4f\n', test_metrics.R2, test_metrics.RMSE, test_metrics.MAE);

%% ----------------------------- SAVE ----------------------------------
results = struct();
results.config.DATA_PATH = DATA_PATH;
results.config.FEATURE_NAMES = FEATURE_NAMES;
results.config.feat_names_used = feat_names_used;
results.config.LABEL_NAME = LABEL_NAME;
results.config.USE_LOG_FEATURES = USE_LOG_FEATURES;
results.config.STANDARDIZE_X = STANDARDIZE_X;
results.config.USE_ONLY_CONVERGED_FIT = USE_ONLY_CONVERGED_FIT;
results.config.USE_PSD_FEATURE = USE_PSD_FEATURE;
results.config.PSD_MAT_PATH = PSD_MAT_PATH;
results.config.PSD_FEAT_USE = PSD_FEAT_USE;
results.config.PSD_FEAT_TRANSFORM = PSD_FEAT_TRANSFORM;
results.config.psd_info = psd_info;
results.config.RNG_SEED = RNG_SEED;
results.config.TUNE_MODE = TUNE_MODE;
results.config.TUNE_METRIC = TUNE_METRIC;
results.config.BAYES_MAX_EVALS = BAYES_MAX_EVALS;
results.config.BAYES_NUM_SEED_POINTS = BAYES_NUM_SEED_POINTS;
results.config.BAYES_ACQ = BAYES_ACQ;
results.split.all_loads = all_loads;
results.split.test_loads = test_loads;
results.split.trainval_loads = trainval_loads;
results.split.fold_val_loads = fold_val_loads;
results.best_candidate = bestCand;
results.cv = bestDetail;
results.test.y_true = y(is_test);
results.test.y_pred = yhat_test;
results.test.metrics = test_metrics;
results.final_model = final_model;
if ~isempty(results_bayes)
    results.bayes = results_bayes;
end

save(fullfile(SAVE_DIR, 'SYN_ML_SVR_PSD.mat'), 'results');
writetable(bestDetail.fold_info, fullfile(SAVE_DIR, 'SYN_ML_SVR_SOH_LoadCV_Bayes_fold_info.csv'));

if ~isempty(results_bayes)
    try
        bayesTable = results_bayes.XTrace;
        bayesTable.Objective = results_bayes.ObjectiveTrace;
        writetable(bayesTable, fullfile(SAVE_DIR, 'SYN_ML_SVR_SOH_LoadCV_Bayes_trace.csv'));
    catch
        warning('Could not save Bayesian optimization trace as CSV. Results object is still saved in MAT file.');
    end
end

%% ----------------------------- PLOT ----------------------------------
if MAKE_PLOTS
    f = figure('Color','w','Name','SVR Synthetic SOH - OOF CV and Hold-out Test');
    hold on;

    % Black/gray: out-of-fold validation predictions from load-level CV.
    h_cv = scatter(results.cv.y_true, results.cv.y_pred, ...
        34, [0.15 0.15 0.15], 'filled', ...
        'MarkerFaceAlpha', 0.65, ...
        'DisplayName', 'Load-CV validation');

    % Red: predictions on fully held-out test loads.
    h_test = scatter(results.test.y_true, results.test.y_pred, ...
        34, [0.85 0.10 0.10], 'filled', ...
        'MarkerFaceAlpha', 0.65, ...
        'DisplayName', 'Hold-out test');

    h_line = plotUnity([results.cv.y_true; results.test.y_true], ...
                       [results.cv.y_pred; results.test.y_pred]);
    set(h_line, 'DisplayName', 'Ideal line');

    xlabel('True SOH_DRT');
    ylabel('Predicted SOH_DRT');
    title(sprintf('SVR SOH Prediction\nCV-Val: R^2=%.3f, RMSE=%.3f | Test: R^2=%.3f, RMSE=%.3f', ...
        bestDetail.metrics_pooled.R2, bestDetail.metrics_pooled.RMSE, test_metrics.R2, test_metrics.RMSE));
    legend([h_cv, h_test, h_line], 'Location','best');
    grid on; axis square; box on;

    exportgraphics(f, fullfile(SAVE_DIR, 'SYN_ML_SVR_SOH_LoadCV_Bayes_OOF_Test_scatter.png'), 'Resolution', 300);
end

fprintf('\nSaved to: %s\n', SAVE_DIR);

%% ============================= HELPERS ===============================
function Dataset = localLoadSyntheticDataset(path0)
    path0 = string(path0);
    if endsWith(lower(path0), '.mat')
        S = load(path0);
        if isfield(S, 'Dataset')
            Dataset = S.Dataset;
        else
            f = fieldnames(S);
            idx = find(structfun(@istable, S), 1);
            if isempty(idx), error('MAT file does not contain a table.'); end
            Dataset = S.(f{idx});
        end
    elseif endsWith(lower(path0), '.csv')
        Dataset = readtable(path0);
    else
        error('DATA_PATH must be .mat or .csv');
    end
end


function [X_psd, psd_feat_names, psd_info] = localBuildPSDFeatureMatrix(psdPath, load_id, featUse, featTransform)
    psdPath = string(psdPath);
    featUse = string(featUse);
    featTransform = string(featTransform);

    if numel(featUse) == 0
        X_psd = zeros(numel(load_id), 0);
        psd_feat_names = {};
        psd_info = struct('matched_loads', strings(0,1), 'missing_loads', strings(0,1));
        return;
    end

    if ~isfile(psdPath)
        error('PSD_MAT_PATH does not exist: %s', psdPath);
    end

    Sp = load(psdPath, 'psd_stat_tbl');
    if ~isfield(Sp, 'psd_stat_tbl')
        error('psd_stat_tbl variable was not found in PSD_MAT_PATH: %s', psdPath);
    end
    psd_tbl = Sp.psd_stat_tbl;

    if ~ismember('Load', psd_tbl.Properties.VariableNames)
        error('psd_stat_tbl must contain a Load column.');
    end

    miss = ~ismember(featUse, string(psd_tbl.Properties.VariableNames));
    if any(miss)
        error('psd_stat_tbl does not contain selected PSD feature(s): %s', strjoin(featUse(miss), ', '));
    end

    n = numel(load_id);
    p = numel(featUse);
    X_psd = nan(n, p);
    psd_feat_names = cell(1,p);
    for j = 1:p
        psd_feat_names{j} = char(sprintf('PSD_%s_%s', featUse(j), upper(featTransform(j))));
    end

    unique_loads = unique(string(load_id), 'stable');
    matched = strings(0,1);
    missing = strings(0,1);

    for i = 1:numel(unique_loads)
        L = unique_loads(i);
        [rowIdx, matchName] = localFindPSDRow(psd_tbl, L);
        m = string(load_id) == L;

        if isnan(rowIdx)
            warning('PSD row not found for load_name=%s. PSD features become NaN for this load.', L);
            missing(end+1,1) = L; %#ok<AGROW>
            continue;
        end

        vec = nan(1,p);
        for j = 1:p
            val = psd_tbl{rowIdx, char(featUse(j))};
            vec(j) = localApplyPSDTransform(val, featTransform(j), featUse(j), L);
        end
        X_psd(m,:) = repmat(vec, nnz(m), 1);
        matched(end+1,1) = sprintf('%s -> %s', L, matchName); %#ok<AGROW>
    end

    fprintf('[PSD] PSD_MAT_PATH: %s\n', psdPath);
    fprintf('[PSD] Appended PSD features (%d): %s\n', p, strjoin(string(psd_feat_names), ', '));
    if ~isempty(matched)
        fprintf('[PSD] Matched loads: %s\n', strjoin(matched, ', '));
    end
    if ~isempty(missing)
        fprintf('[PSD] Missing loads: %s\n', strjoin(missing, ', '));
    end

    psd_info = struct();
    psd_info.psdPath = psdPath;
    psd_info.featUse = featUse;
    psd_info.featTransform = featTransform;
    psd_info.matched_loads = matched;
    psd_info.missing_loads = missing;
end

function [rowIdx, matchName] = localFindPSDRow(psd_tbl, loadName)
    psd_load_raw = string(psd_tbl.Load);
    psd_clean = strings(size(psd_load_raw));
    for ii = 1:numel(psd_load_raw)
        psd_clean(ii) = localCleanLoadName(psd_load_raw(ii));
    end
    q = localCleanLoadName(loadName);

    rowIdx = NaN;
    matchName = "";

    m = (psd_clean == q);
    if any(m)
        rowIdx = find(m, 1, 'first');
        matchName = psd_load_raw(rowIdx);
        return;
    end

    m = false(size(psd_clean));
    for k = 1:numel(psd_clean)
        a = psd_clean(k);
        m(k) = contains(a, q) || contains(q, a);
    end
    if any(m)
        rowIdx = find(m, 1, 'first');
        matchName = psd_load_raw(rowIdx);
    end
end

function s = localCleanLoadName(x)
    s = upper(string(x));
    s = erase(s, '"');
    s = replace(s, char(39), '');
    s = strtrim(s);
    s = strrep(s, '-', '_');
    s = regexprep(s, '\s+', '_');
    s = regexprep(s, '_+', '_');
    s = regexprep(s, '^_+|_+$', '');
end

function out = localApplyPSDTransform(x, mode, featName, loadName)
    x = double(x);
    mode = lower(string(mode));

    if isempty(x) || ~isfinite(x)
        out = NaN;
        return;
    end

    switch mode
        case "none"
            out = x;
        case "log10"
            if x <= 0
                warning('PSD feature %s for load %s is <=0, so log10 transform returns NaN.', string(featName), string(loadName));
                out = NaN;
            else
                out = log10(x);
            end
        case "log1p"
            if x <= -1
                warning('PSD feature %s for load %s is <=-1, so log1p transform returns NaN.', string(featName), string(loadName));
                out = NaN;
            else
                out = log1p(x);
            end
        otherwise
            error('Unknown PSD transform mode: %s', mode);
    end
end

function loads = parseLoadList(str0)
    str0 = string(str0);
    if strlength(strtrim(str0)) == 0
        loads = strings(0,1);
        return;
    end
    parts = regexp(strtrim(str0), '[,;\s]+', 'split');
    loads = string(parts(:));
    loads(loads=="") = [];
end

function candidates = makeRandomCandidates(N, kernelSet, logC, logEps, logKS, allowAutoKS)
    candidates = repmat(struct('KernelFunction','linear','BoxConstraint',1, ...
        'Epsilon',0.1,'KernelScale','auto'), N, 1);
    for i = 1:N
        ker = kernelSet{randi(numel(kernelSet))};
        C = 10^(logC(1) + diff(logC)*rand());
        eps0 = 10^(logEps(1) + diff(logEps)*rand());
        if strcmpi(ker, 'linear')
            ks = 'auto';
        else
            if allowAutoKS && rand() < 0.25
                ks = 'auto';
            else
                ks = 10^(logKS(1) + diff(logKS)*rand());
            end
        end
        candidates(i).KernelFunction = ker;
        candidates(i).BoxConstraint = C;
        candidates(i).Epsilon = eps0;
        candidates(i).KernelScale = ks;
    end
end

function [score, detail] = evalLoadCV_SVR(X, y, load_id, trainval_loads, fold_val_loads, kernel, C, eps0, ks, doStd, metric)
    K = numel(fold_val_loads);
    yhat_cv = nan(size(y));
    fold_R2 = nan(K,1);
    fold_RMSE = nan(K,1);
    fold_MAE = nan(K,1);
    fold_info = table();
    for k = 1:K
        val_loads = fold_val_loads{k};
        tr_loads = setdiff(trainval_loads, val_loads, 'stable');
        is_tr = ismember(load_id, tr_loads);
        is_val = ismember(load_id, val_loads);

        try
            mdl = fitrsvm(X(is_tr,:), y(is_tr), ...
                'KernelFunction', kernel, ...
                'BoxConstraint', C, ...
                'Epsilon', eps0, ...
                'KernelScale', ks, ...
                'Standardize', doStd);
            yhat = predict(mdl, X(is_val,:));
            yhat_cv(is_val) = yhat;
            m = calcMetrics(y(is_val), yhat);
            fold_R2(k) = m.R2;
            fold_RMSE(k) = m.RMSE;
            fold_MAE(k) = m.MAE;
        catch ME
            warning('SVR fit/predict failed at fold %d. %s', k, ME.message);
            m = struct('R2',NaN,'RMSE',NaN,'MAE',NaN);
        end

        fold_info = [fold_info; table(k, string(strjoin(cellstr(tr_loads), ', ')), ...
            string(strjoin(cellstr(val_loads), ', ')), nnz(is_tr), nnz(is_val), ...
            m.R2, m.RMSE, m.MAE, ...
            'VariableNames', {'fold','train_loads','val_loads','n_train','n_val','R2','RMSE','MAE'})]; %#ok<AGROW>
    end

    is_tv = ismember(load_id, trainval_loads);
    metrics_pooled = calcMetrics(y(is_tv), yhat_cv(is_tv));

    switch upper(string(metric))
        case "MAE"
            score = metrics_pooled.MAE;
        otherwise
            score = metrics_pooled.RMSE;
    end

    if ~isfinite(score)
        score = 1e12;
    end

    detail.fold_info = fold_info;
    detail.y_true = y(is_tv);
    detail.y_pred = yhat_cv(is_tv);
    detail.fold_R2 = fold_R2;
    detail.fold_RMSE = fold_RMSE;
    detail.fold_MAE = fold_MAE;
    detail.metrics_pooled = metrics_pooled;
end

function objective = bayesObjectiveLoadCV_SVR(T, X, y, load_id, trainval_loads, fold_val_loads, doStd, metric)
    cand = bayesTableToCandidate(T);
    try
        [objective, ~] = evalLoadCV_SVR(X, y, load_id, trainval_loads, fold_val_loads, ...
            cand.KernelFunction, cand.BoxConstraint, cand.Epsilon, ...
            cand.KernelScale, doStd, metric);
        if ~isfinite(objective)
            objective = 1e12;
        end
    catch ME
        warning('Bayes objective failed. %s', ME.message);
        objective = 1e12;
    end
end

function cand = bayesTableToCandidate(T)
    if istable(T)
        kernelType = T.kernelType(1);
        log10C = T.log10C(1);
        log10Epsilon = T.log10Epsilon(1);
        log10KernelScale = T.log10KernelScale(1);
    else
        kernelType = T.kernelType;
        log10C = T.log10C;
        log10Epsilon = T.log10Epsilon;
        log10KernelScale = T.log10KernelScale;
    end

    if kernelType == 1
        kernel = 'linear';
        kernelScale = 'auto';
    else
        kernel = 'gaussian';
        kernelScale = 10.^log10KernelScale;
    end

    cand = struct();
    cand.KernelFunction = kernel;
    cand.BoxConstraint = 10.^log10C;
    cand.Epsilon = 10.^log10Epsilon;
    cand.KernelScale = kernelScale;
end

function m = calcMetrics(y, yhat)
    y = y(:); yhat = yhat(:);
    ok = isfinite(y) & isfinite(yhat);
    y = y(ok); yhat = yhat(ok);
    if isempty(y)
        m.R2 = NaN; m.RMSE = NaN; m.MAE = NaN;
        return;
    end
    res = yhat - y;
    m.RMSE = sqrt(mean(res.^2));
    m.MAE = mean(abs(res));
    denom = sum((y - mean(y)).^2);
    if denom <= eps
        m.R2 = NaN;
    else
        m.R2 = 1 - sum(res.^2) / denom;
    end
end

function s = ks2str(ks)
    if isnumeric(ks)
        s = sprintf('%.4g', ks);
    else
        s = char(string(ks));
    end
end

function h = plotUnity(y, yhat)
    mn = min([y(:); yhat(:)]);
    mx = max([y(:); yhat(:)]);
    if ~isfinite(mn) || ~isfinite(mx) || mn==mx
        mn = 0; mx = 1;
    end
    pad = 0.05*(mx-mn);
    lo = mn-pad; hi = mx+pad;
    h = plot([lo hi], [lo hi], 'k--', 'LineWidth', 1.2);
    xlim([lo hi]); ylim([lo hi]);
end
