%% ======================================================================
% SYN_ML_MLR_SOH_LoadCV.m
% ----------------------------------------------------------------------
% Synthetic DRT-SOH dataset -> MLR
%
% [DATA]
%   Input MAT/CSV is generated by Synthesis_DRT_SOH.m
%   Required table columns:
%     Feature: R0_hat, R1_hat, R2_hat, tau1_hat, tau2_hat
%     Label  : SOH_DRT
%     Group  : load_name
%
% [SPLIT]
%   Load-level split.
%   If total loads = 20:
%     fixed test loads = 4
%     remaining train/val loads = 16
%     K-fold CV with K=4 -> each fold train:val:test = 12:4:4 loads
%
% [MODEL]
%   Multiple Linear Regression using fitlm.
% ======================================================================
clear; clc; close all;

set(groot,'defaultTextInterpreter','none');
set(groot,'defaultAxesTickLabelInterpreter','none');
set(groot,'defaultLegendInterpreter','none');

%% ----------------------------- CONFIG --------------------------------
DATA_PATH = "G:\공유 드라이브\Battery Software Group (2025)\Members\김주은\PINN\합성데이터\Synthetic_DRT_SOH_Dataset_DRTLabel_CellRef.mat";
SAVE_DIR  = "G:\공유 드라이브\Battery Software Group (2025)\Members\김주은\PINN\합성데이터\ML_MLR_SOH";
if ~exist(SAVE_DIR, 'dir'), mkdir(SAVE_DIR); end

% Features from fitted 2RC ECM parameters.
FEATURE_NAMES = {'R0_hat','R1_hat','R2_hat','tau1_hat','tau2_hat'};
LABEL_NAME    = 'SOH_DRT';
LOAD_COL      = 'load_name';

% Optional filtering.
USE_ONLY_CONVERGED_FIT = true;   % true: exitflag > 0 if exitflag column exists
USE_LOG_FEATURES = true;         % recommended for positive ECM parameters
STANDARDIZE_X    = true;         % z-score using training fold only

% Load split.
RNG_SEED = 1;
N_TEST_LOAD = 4;
N_VAL_LOAD_PER_FOLD = 4;         % with 16 trainval loads -> K=4
TEST_LOAD_STR = "";             % e.g. "US06 UDDS HWFET WLTP". Empty -> random 4 loads

% Plot toggle.
MAKE_PLOTS = true;

%% ----------------------------- LOAD DATA -----------------------------
Dataset = localLoadSyntheticDataset(DATA_PATH);

% Validate columns.
needCols = [FEATURE_NAMES, {LABEL_NAME, LOAD_COL}];
for i = 1:numel(needCols)
    if ~ismember(needCols{i}, Dataset.Properties.VariableNames)
        error('Dataset does not contain required column: %s', needCols{i});
    end
end

X = Dataset{:, FEATURE_NAMES};
y = Dataset{:, LABEL_NAME};
load_id = string(Dataset{:, LOAD_COL});

valid = all(isfinite(X),2) & isfinite(y) & strlength(load_id)>0;
if USE_ONLY_CONVERGED_FIT && ismember('exitflag', Dataset.Properties.VariableNames)
    valid = valid & Dataset.exitflag > 0;
end

X = X(valid,:);
y = y(valid,:);
load_id = load_id(valid,:);

if USE_LOG_FEATURES
    if any(X(:) <= 0)
        error('USE_LOG_FEATURES=true but some ECM features are <= 0. Check fitted parameters.');
    end
    X = log10(X);
    feat_names_used = strcat('log10_', FEATURE_NAMES);
else
    feat_names_used = FEATURE_NAMES;
end

all_loads = unique(load_id, 'stable');
nLoads = numel(all_loads);
fprintf('[DATA] valid samples = %d | loads = %d | features = %d\n', size(X,1), nLoads, size(X,2));
fprintf('[LOADS] %s\n', strjoin(cellstr(all_loads), ', '));

%% ----------------------------- LOAD SPLIT ----------------------------
rng(RNG_SEED, 'twister');

if strlength(strtrim(TEST_LOAD_STR)) > 0
    test_loads = parseLoadList(TEST_LOAD_STR);
    test_loads = intersect(test_loads, all_loads, 'stable');
else
    if nLoads < N_TEST_LOAD + N_VAL_LOAD_PER_FOLD
        error('Not enough loads for requested split. nLoads=%d', nLoads);
    end
    p = randperm(nLoads);
    test_loads = all_loads(sort(p(1:N_TEST_LOAD)));
end

trainval_loads = setdiff(all_loads, test_loads, 'stable');
if mod(numel(trainval_loads), N_VAL_LOAD_PER_FOLD) ~= 0
    warning('numel(trainval_loads)=%d is not divisible by N_VAL_LOAD_PER_FOLD=%d. Last fold size may differ.', ...
        numel(trainval_loads), N_VAL_LOAD_PER_FOLD);
end
K = ceil(numel(trainval_loads) / N_VAL_LOAD_PER_FOLD);

% Assign trainval loads to validation folds.
p = randperm(numel(trainval_loads));
cv_loads_shuffled = trainval_loads(p);
fold_val_loads = cell(K,1);
for k = 1:K
    idx1 = (k-1)*N_VAL_LOAD_PER_FOLD + 1;
    idx2 = min(k*N_VAL_LOAD_PER_FOLD, numel(cv_loads_shuffled));
    fold_val_loads{k} = cv_loads_shuffled(idx1:idx2);
end

fprintf('\n[SPLIT]\n');
fprintf('  Test loads (%d): %s\n', numel(test_loads), strjoin(cellstr(test_loads), ', '));
fprintf('  Train/Val loads (%d): %s\n', numel(trainval_loads), strjoin(cellstr(trainval_loads), ', '));
fprintf('  CV folds = %d | val loads per fold = %d\n', K, N_VAL_LOAD_PER_FOLD);

%% ----------------------------- LOAD-LEVEL CV -------------------------
yhat_cv = nan(size(y));
fold_R2 = nan(K,1);
fold_RMSE = nan(K,1);
fold_MAE = nan(K,1);
fold_info = table();
models_cv = cell(K,1);

for k = 1:K
    val_loads = fold_val_loads{k};
    tr_loads = setdiff(trainval_loads, val_loads, 'stable');

    is_tr  = ismember(load_id, tr_loads);
    is_val = ismember(load_id, val_loads);

    [Xtr, muX, sigX] = localStandardizeTrain(X(is_tr,:), STANDARDIZE_X);
    Xval = localApplyStandardize(X(is_val,:), muX, sigX, STANDARDIZE_X);

    mdl = fitlm(Xtr, y(is_tr));
    yhat = predict(mdl, Xval);
    yhat_cv(is_val) = yhat;
    models_cv{k} = mdl;

    m = calcMetrics(y(is_val), yhat);
    fold_R2(k) = m.R2;
    fold_RMSE(k) = m.RMSE;
    fold_MAE(k) = m.MAE;

    fprintf('\n[FOLD %d/%d]\n', k, K);
    fprintf('  Train loads (%d): %s\n', numel(tr_loads), strjoin(cellstr(tr_loads), ', '));
    fprintf('  Val loads   (%d): %s\n', numel(val_loads), strjoin(cellstr(val_loads), ', '));
    fprintf('  Val: R2=%.4f | RMSE=%.4f | MAE=%.4f\n', m.R2, m.RMSE, m.MAE);

    fold_info = [fold_info; table(k, string(strjoin(cellstr(tr_loads), ', ')), ...
        string(strjoin(cellstr(val_loads), ', ')), nnz(is_tr), nnz(is_val), ...
        m.R2, m.RMSE, m.MAE, ...
        'VariableNames', {'fold','train_loads','val_loads','n_train','n_val','R2','RMSE','MAE'})]; %#ok<AGROW>
end

is_tv = ismember(load_id, trainval_loads);
is_test = ismember(load_id, test_loads);
cv_metrics = calcMetrics(y(is_tv), yhat_cv(is_tv));
fprintf('\n[LOAD-CV SUMMARY]\n');
fprintf('  Mean fold: R2=%.4f | RMSE=%.4f | MAE=%.4f\n', mean(fold_R2,'omitnan'), mean(fold_RMSE,'omitnan'), mean(fold_MAE,'omitnan'));
fprintf('  Pooled CV: R2=%.4f | RMSE=%.4f | MAE=%.4f\n', cv_metrics.R2, cv_metrics.RMSE, cv_metrics.MAE);

%% ----------------------------- FINAL TEST ----------------------------
[Xtv, muX_final, sigX_final] = localStandardizeTrain(X(is_tv,:), STANDARDIZE_X);
Xtest = localApplyStandardize(X(is_test,:), muX_final, sigX_final, STANDARDIZE_X);

final_model = fitlm(Xtv, y(is_tv));
yhat_test = predict(final_model, Xtest);
test_metrics = calcMetrics(y(is_test), yhat_test);

fprintf('\n[FINAL TEST]\n');
fprintf('  Train loads = %d | Test loads = %d\n', numel(trainval_loads), numel(test_loads));
fprintf('  Test: R2=%.4f | RMSE=%.4f | MAE=%.4f\n', test_metrics.R2, test_metrics.RMSE, test_metrics.MAE);

%% ----------------------------- SAVE ----------------------------------
results = struct();
results.config.DATA_PATH = DATA_PATH;
results.config.FEATURE_NAMES = FEATURE_NAMES;
results.config.feat_names_used = feat_names_used;
results.config.LABEL_NAME = LABEL_NAME;
results.config.USE_LOG_FEATURES = USE_LOG_FEATURES;
results.config.STANDARDIZE_X = STANDARDIZE_X;
results.config.USE_ONLY_CONVERGED_FIT = USE_ONLY_CONVERGED_FIT;
results.config.RNG_SEED = RNG_SEED;
results.split.all_loads = all_loads;
results.split.test_loads = test_loads;
results.split.trainval_loads = trainval_loads;
results.split.fold_val_loads = fold_val_loads;
results.cv.fold_info = fold_info;
results.cv.y_true = y(is_tv);
results.cv.y_pred = yhat_cv(is_tv);
results.cv.metrics_pooled = cv_metrics;
results.cv.fold_R2 = fold_R2;
results.cv.fold_RMSE = fold_RMSE;
results.cv.fold_MAE = fold_MAE;
results.test.y_true = y(is_test);
results.test.y_pred = yhat_test;
results.test.metrics = test_metrics;
results.final_model = final_model;
results.final_standardizer.muX = muX_final;
results.final_standardizer.sigX = sigX_final;

save(fullfile(SAVE_DIR, 'SYN_ML_MLR_SOH_LoadCV_results.mat'), 'results');
writetable(fold_info, fullfile(SAVE_DIR, 'SYN_ML_MLR_SOH_LoadCV_fold_info.csv'));

if MAKE_PLOTS
    f = figure('Color','w','Name','MLR Synthetic SOH - OOF CV and Hold-out Test');
    hold on;

    % Black/gray: out-of-fold validation predictions from load-level CV.
    h_cv = scatter(results.cv.y_true, results.cv.y_pred, ...
        34, [0.15 0.15 0.15], 'filled', ...
        'MarkerFaceAlpha', 0.45, ...
        'DisplayName', 'Load-CV validation');

    % Blue: predictions on fully held-out test loads.
    h_test = scatter(results.test.y_true, results.test.y_pred, ...
        34, [0.85 0.10 0.10], 'filled', ...
        'MarkerFaceAlpha', 0.45, ...
        'DisplayName', 'Hold-out test');

    h_line = plotUnity([results.cv.y_true; results.test.y_true], ...
        [results.cv.y_pred; results.test.y_pred]);
    set(h_line, 'DisplayName', 'Ideal line');

    xlabel('True SOH_DRT');
    ylabel('Predicted SOH_DRT');
    title(sprintf('MLR SOH Prediction\nCV-Val: R^2=%.3f, RMSE=%.3f | Test: R^2=%.3f, RMSE=%.3f', ...
        cv_metrics.R2, cv_metrics.RMSE, test_metrics.R2, test_metrics.RMSE));
    legend([h_cv, h_test, h_line], 'Location','best');
    grid on; axis square; box on;

    exportgraphics(f, fullfile(SAVE_DIR, 'SYN_ML_MLR_SOH_LoadCV_OOF_Test_scatter.png'), 'Resolution', 300);
end

fprintf('\nSaved to: %s\n', SAVE_DIR);

%% ============================= HELPERS ===============================
function Dataset = localLoadSyntheticDataset(path0)
    path0 = string(path0);
    if endsWith(lower(path0), '.mat')
        S = load(path0);
        if isfield(S, 'Dataset')
            Dataset = S.Dataset;
        else
            f = fieldnames(S);
            idx = find(structfun(@istable, S), 1);
            if isempty(idx), error('MAT file does not contain a table.'); end
            Dataset = S.(f{idx});
        end
    elseif endsWith(lower(path0), '.csv')
        Dataset = readtable(path0);
    else
        error('DATA_PATH must be .mat or .csv');
    end
end

function loads = parseLoadList(str0)
    str0 = string(str0);
    if strlength(strtrim(str0)) == 0
        loads = strings(0,1);
        return;
    end
    parts = regexp(strtrim(str0), '[,;\s]+', 'split');
    loads = string(parts(:));
    loads(loads=="") = [];
end

function [Xs, muX, sigX] = localStandardizeTrain(X, doStd)
    if doStd
        muX = mean(X,1,'omitnan');
        sigX = std(X,0,1,'omitnan');
        sigX(sigX==0 | ~isfinite(sigX)) = 1;
        Xs = (X - muX) ./ sigX;
    else
        muX = zeros(1,size(X,2));
        sigX = ones(1,size(X,2));
        Xs = X;
    end
end

function Xs = localApplyStandardize(X, muX, sigX, doStd)
    if doStd
        Xs = (X - muX) ./ sigX;
    else
        Xs = X;
    end
end

function m = calcMetrics(y, yhat)
    y = y(:); yhat = yhat(:);
    ok = isfinite(y) & isfinite(yhat);
    y = y(ok); yhat = yhat(ok);
    res = yhat - y;
    m.RMSE = sqrt(mean(res.^2));
    m.MAE = mean(abs(res));
    denom = sum((y - mean(y)).^2);
    if denom <= eps
        m.R2 = NaN;
    else
        m.R2 = 1 - sum(res.^2) / denom;
    end
end

function h = plotUnity(y, yhat)
    mn = min([y(:); yhat(:)]);
    mx = max([y(:); yhat(:)]);
    if ~isfinite(mn) || ~isfinite(mx) || mn==mx
        mn = 0; mx = 1;
    end
    pad = 0.05*(mx-mn);
    lo = mn-pad; hi = mx+pad;
    h = plot([lo hi], [lo hi], 'k--', 'LineWidth', 1.2);
    xlim([lo hi]); ylim([lo hi]);
end
